# Keycloak — prod
image:
  registry: harbor.ai.adports.ae
  repository: bitnami/keycloak
  tag: "25.0.6"
replicaCount: 3
auth:
  existingSecret: keycloak-admin-creds
  passwordSecretKey: admin-password
extraEnvVars:
  - name: KC_HOSTNAME
    value: auth.ai.adports.ae
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_PROXY
    value: edge
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL
    value: jdbc:postgresql://orbit-postgres-prod-rw.ai-portal-data.svc.cluster.local:5432/ai_portal_keycloak
  - name: KC_DB_USERNAME
    value: orbit_app
  - name: KC_FEATURES
    value: token-exchange,fine-grained-authz
  - name: KC_LOG_LEVEL
    value: INFO
  - name: JAVA_OPTS_APPEND
    value: "-Djgroups.dns.query=keycloak-headless"
extraEnvVarsSecret: keycloak-db-creds
resources:
  requests: { memory: 1Gi, cpu: 500m }
  limits:   { memory: 2Gi, cpu: 1 }
metrics:
  enabled: true
  serviceMonitor: { enabled: true }
podDisruptionBudget:
  create: true
  minAvailable: 2
