# Strimzi Kafka operator — prod
image:
  registry: harbor.ai.adports.ae
  repository: strimzi/operator
  tag: "0.43.0"
watchAnyNamespace: false
resources:
  requests: { cpu: 200m, memory: 384Mi }
  limits:   { cpu: 500m, memory: 512Mi }
logLevel: INFO
