# Kong Ingress Controller — dev
image:
  repository: harbor.ai.adports.ae/kong/kong-gateway
  tag: "3.8.0"
ingressController:
  image:
    repository: harbor.ai.adports.ae/kong/kubernetes-ingress-controller
    tag: "3.3.1"
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits:   { cpu: 250m, memory: 256Mi }

proxy:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: orbit-pool
  resources:
    requests: { cpu: 200m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }

env:
  database: "off"
  router_flavor: expressions
  proxy_stream_error_log: /dev/stderr
  admin_gui_url: https://kong-admin.ai.adports.ae
  admin_api_uri: https://kong-admin.ai.adports.ae

admin:
  enabled: true
  type: ClusterIP

# TLS is terminated by cert-manager + Kong plugin
