apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: orbit
  namespace: argocd
spec:
  description: ORBIT AI Platform
  sourceRepos:
    - https://github.com/linoymalakkaran/ORBIT.git
    - https://charts.helm.sh/stable
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://strimzi.io/charts/
    - https://temporalio.github.io/helm-charts
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
