"""DevOps & Infrastructure Agent — generates GitLab CI pipelines, Helm charts, Kong routes,
ArgoCD app manifests, and security tool configs (SonarQube, Trivy, Checkmarx)."""
from __future__ import annotations

import logging
import textwrap
from typing import Annotated, TypedDict
import operator

import httpx
import litellm
from fastapi import FastAPI
from langgraph.graph import END, StateGraph
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from pydantic import BaseModel
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="DEVOPS_", env_file=".env", extra="ignore")
    litellm_api_base: str = "http://litellm-gateway.litellm.svc:4000"
    litellm_api_key: str = "changeme"
    default_model: str = "gpt-4o"
    ledger_url: str = "http://pipeline-ledger.ai-portal.svc:80"
    harbor_registry: str = "harbor.ai.adports.ae/orbit"
    argocd_repo: str = "https://github.com/linoymalakkaran/ORBIT.git"


settings = Settings()
litellm.api_base = settings.litellm_api_base
litellm.api_key = settings.litellm_api_key


class DevOpsGenState(TypedDict):
    project_id: str
    service_name: str
    service_type: str           # "dotnet" | "python" | "angular"
    has_frontend: bool
    gitlab_ci: str
    helm_chart: str
    kong_plugin_config: str
    argocd_app: str
    sonarqube_config: str
    trivy_config: str
    security_pipeline_stages: str


async def _llm(prompt: str, system: str = "You are a senior DevOps engineer.") -> str:
    r = await litellm.acompletion(
        model=settings.default_model,
        messages=[{"role": "system", "content": system}, {"role": "user", "content": prompt}],
        temperature=0.05,
    )
    return r.choices[0].message.content or ""


async def generate_gitlab_ci(state: DevOpsGenState) -> dict:
    svc = state["service_name"]
    svc_lower = svc.lower()
    service_type = state["service_type"]

    if service_type == "dotnet":
        build_cmd = "dotnet build --configuration Release"
        test_cmd = "dotnet test --configuration Release --logger junit --results-directory test-results"
        docker_context = f"src/{svc}"
    elif service_type == "angular":
        build_cmd = f"npx nx build {svc_lower} --configuration production"
        test_cmd = f"npx nx test {svc_lower} --ci"
        docker_context = f"src/{svc_lower}"
    else:  # python
        build_cmd = "pip install poetry && poetry install"
        test_cmd = "poetry run pytest --junitxml=test-results/junit.xml"
        docker_context = f"src/{svc_lower}"

    ci_yaml = textwrap.dedent(f"""\
        # GitLab CI/CD — {svc}
        # Generated by ORBIT DevOps Agent

        variables:
          SERVICE_NAME: "{svc_lower}"
          HARBOR_REGISTRY: "harbor.ai.adports.ae/orbit"
          IMAGE_TAG: "$CI_COMMIT_SHA"
          SONAR_HOST_URL: "https://sonarqube.ai.adports.ae"
          ARGOCD_SERVER: "argocd.ai.adports.ae"

        stages:
          - lint
          - test
          - security-scan
          - build
          - push
          - trivy-scan
          - deploy-dev
          - deploy-prod

        # ── Lint ────────────────────────────────────────────────────────────
        lint:
          stage: lint
          image: harbor.ai.adports.ae/orbit/ci-tools:latest
          script:
            - echo "Linting {svc}..."
          rules:
            - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
            - if: '$CI_COMMIT_BRANCH == "main"'

        # ── Test ─────────────────────────────────────────────────────────────
        test:
          stage: test
          image: harbor.ai.adports.ae/orbit/ci-tools:latest
          script:
            - {build_cmd}
            - {test_cmd}
          artifacts:
            reports:
              junit: test-results/junit.xml
            expire_in: 7 days

        # ── SonarQube SAST ───────────────────────────────────────────────────
        sonarqube-scan:
          stage: security-scan
          image: harbor.ai.adports.ae/orbit/sonar-scanner:latest
          script:
            - sonar-scanner
              -Dsonar.projectKey={svc_lower}
              -Dsonar.sources=.
              -Dsonar.host.url=$SONAR_HOST_URL
              -Dsonar.login=$SONAR_TOKEN
              -Dsonar.qualitygate.wait=true
          allow_failure: false

        # ── Docker Build ─────────────────────────────────────────────────────
        build:
          stage: build
          image: harbor.ai.adports.ae/orbit/kaniko:latest
          script:
            - /kaniko/executor
              --context $CI_PROJECT_DIR/{docker_context}
              --dockerfile $CI_PROJECT_DIR/{docker_context}/Dockerfile
              --destination $HARBOR_REGISTRY/$SERVICE_NAME:$IMAGE_TAG
              --destination $HARBOR_REGISTRY/$SERVICE_NAME:latest
              --registry-mirror harbor.ai.adports.ae
          rules:
            - if: '$CI_COMMIT_BRANCH == "main"'

        # ── Trivy Container Scan ─────────────────────────────────────────────
        trivy-scan:
          stage: trivy-scan
          image: harbor.ai.adports.ae/orbit/trivy:latest
          script:
            - trivy image
              --exit-code 1
              --severity CRITICAL
              --no-progress
              $HARBOR_REGISTRY/$SERVICE_NAME:$IMAGE_TAG
          rules:
            - if: '$CI_COMMIT_BRANCH == "main"'

        # ── Deploy Dev ───────────────────────────────────────────────────────
        deploy-dev:
          stage: deploy-dev
          image: harbor.ai.adports.ae/orbit/argocd-cli:latest
          script:
            - argocd login $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --insecure
            - argocd app set {svc_lower}-dev --kustomize-image $HARBOR_REGISTRY/$SERVICE_NAME:$IMAGE_TAG
            - argocd app sync {svc_lower}-dev --prune --timeout 300
          environment:
            name: dev
          rules:
            - if: '$CI_COMMIT_BRANCH == "main"'

        # ── Deploy Prod (manual gate) ────────────────────────────────────────
        deploy-prod:
          stage: deploy-prod
          image: harbor.ai.adports.ae/orbit/argocd-cli:latest
          script:
            - argocd login $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --insecure
            - argocd app set {svc_lower}-prod --kustomize-image $HARBOR_REGISTRY/$SERVICE_NAME:$IMAGE_TAG
            - argocd app sync {svc_lower}-prod --prune --timeout 300
          environment:
            name: prod
          when: manual
          rules:
            - if: '$CI_COMMIT_BRANCH == "main"'
    """)
    return {"gitlab_ci": ci_yaml}


async def generate_helm_chart(state: DevOpsGenState) -> dict:
    svc = state["service_name"]
    svc_lower = svc.lower()
    chart = textwrap.dedent(f"""\
        # Helm Chart — {svc}
        # Chart.yaml
        apiVersion: v2
        name: {svc_lower}
        description: "ORBIT generated service: {svc}"
        type: application
        version: 0.1.0
        appVersion: "1.0.0"

        ---
        # values.yaml
        replicaCount: 2

        image:
          repository: harbor.ai.adports.ae/orbit/{svc_lower}
          tag: latest
          pullPolicy: IfNotPresent

        imagePullSecrets:
          - name: harbor-pull-secret

        nameOverride: ""
        fullnameOverride: ""

        serviceAccount:
          create: true
          name: {svc_lower}

        service:
          type: ClusterIP
          port: 80
          targetPort: 8080

        ingress:
          enabled: true
          className: kong
          annotations:
            cert-manager.io/cluster-issuer: adports-internal-ca
            konghq.com/plugins: jwt-auth,rate-limiting
          host: {svc_lower}.ai.adports.ae
          tls:
            - secretName: {svc_lower}-tls
              hosts:
                - {svc_lower}.ai.adports.ae

        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 8
          targetCPUUtilizationPercentage: 70

        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        vault:
          role: {svc_lower}
          enabled: true

        otel:
          endpoint: "http://otel-collector.monitoring.svc:4317"
          serviceName: {svc_lower}

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
    """)
    return {"helm_chart": chart}


async def generate_kong_config(state: DevOpsGenState) -> dict:
    svc_lower = state["service_name"].lower()
    kong_config = textwrap.dedent(f"""\
        # Kong KongPlugin resources for {state['service_name']}
        apiVersion: configuration.konghq.com/v1
        kind: KongPlugin
        metadata:
          name: {svc_lower}-jwt-auth
          namespace: ai-portal
        plugin: jwt
        config:
          key_claim_name: sub
          claims_to_verify:
            - exp
            - nbf

        ---
        apiVersion: configuration.konghq.com/v1
        kind: KongPlugin
        metadata:
          name: {svc_lower}-rate-limiting
          namespace: ai-portal
        plugin: rate-limiting
        config:
          minute: 1000
          hour: 10000
          policy: redis
          redis_host: redis-master.ai-portal.svc
          redis_port: 6379

        ---
        apiVersion: configuration.konghq.com/v1
        kind: KongPlugin
        metadata:
          name: {svc_lower}-otel
          namespace: ai-portal
        plugin: opentelemetry
        config:
          endpoint: http://otel-collector.monitoring.svc:4318/v1/traces
          resource_attributes:
            service.name: {svc_lower}
    """)
    return {"kong_plugin_config": kong_config}


async def generate_argocd_app(state: DevOpsGenState) -> dict:
    svc_lower = state["service_name"].lower()
    argocd = textwrap.dedent(f"""\
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {svc_lower}-dev
          namespace: argocd
          labels:
            orbit.adports.ae/service: {svc_lower}
            orbit.adports.ae/env: dev
        spec:
          project: orbit
          source:
            repoURL: {settings.argocd_repo}
            targetRevision: main
            path: src/{svc_lower}/k8s
          destination:
            server: https://kubernetes.default.svc
            namespace: ai-portal
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=false
              - ServerSideApply=true
          ignoreDifferences:
            - group: apps
              kind: Deployment
              jsonPointers:
                - /spec/replicas
        ---
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {svc_lower}-prod
          namespace: argocd
          labels:
            orbit.adports.ae/service: {svc_lower}
            orbit.adports.ae/env: prod
        spec:
          project: orbit
          source:
            repoURL: {settings.argocd_repo}
            targetRevision: main
            path: src/{svc_lower}/k8s
          destination:
            server: https://kubernetes.default.svc
            namespace: ai-portal
          syncPolicy:
            syncOptions:
              - CreateNamespace=false
              - ServerSideApply=true
    """)
    return {"argocd_app": argocd}


async def generate_security_configs(state: DevOpsGenState) -> dict:
    svc_lower = state["service_name"].lower()
    sonar = textwrap.dedent(f"""\
        # sonar-project.properties for {state['service_name']}
        sonar.projectKey={svc_lower}
        sonar.projectName={state['service_name']}
        sonar.sources=src/{svc_lower}
        sonar.exclusions=**/*Tests*/**,**/Migrations/**,**/wwwroot/**
        sonar.coverage.exclusions=**/*Tests*/**
        sonar.cs.opencover.reportsPaths=test-results/coverage.opencover.xml
        sonar.qualitygate.wait=true
    """)
    trivy = textwrap.dedent(f"""\
        # .trivyignore for {state['service_name']}
        # Add CVE exceptions here with justification
        # Example: CVE-XXXX-XXXXX  # Not applicable — not using affected feature

        # trivy.yaml
        scan:
          security-checks:
            - vuln
            - config
            - secret
        severity:
          - CRITICAL
          - HIGH
        exit-code: 1
        ignore-unfixed: false
        timeout: 10m
    """)
    return {"sonarqube_config": sonar, "trivy_config": trivy}


def _build_graph():
    g = StateGraph(DevOpsGenState)
    for name, fn in [
        ("generate_gitlab_ci", generate_gitlab_ci),
        ("generate_helm_chart", generate_helm_chart),
        ("generate_kong_config", generate_kong_config),
        ("generate_argocd_app", generate_argocd_app),
        ("generate_security_configs", generate_security_configs),
    ]:
        g.add_node(name, fn)
    g.add_edge("generate_gitlab_ci", "generate_helm_chart")
    g.add_edge("generate_helm_chart", "generate_kong_config")
    g.add_edge("generate_kong_config", "generate_argocd_app")
    g.add_edge("generate_argocd_app", "generate_security_configs")
    g.add_edge("generate_security_configs", END)
    g.set_entry_point("generate_gitlab_ci")
    return g.compile()


_graph = _build_graph()

app = FastAPI(title="ORBIT DevOps & Infrastructure Agent", version="1.0.0")
FastAPIInstrumentor.instrument_app(app)


class DevOpsGenRequest(BaseModel):
    project_id: str
    service_name: str
    service_type: str = "dotnet"   # dotnet | python | angular
    has_frontend: bool = False


@app.post("/api/generate/devops")
async def generate_devops(req: DevOpsGenRequest):
    """Generate full CI/CD pipeline, Helm chart, Kong config, ArgoCD app, security configs."""
    initial: DevOpsGenState = {
        "project_id": req.project_id,
        "service_name": req.service_name,
        "service_type": req.service_type,
        "has_frontend": req.has_frontend,
        "gitlab_ci": "",
        "helm_chart": "",
        "kong_plugin_config": "",
        "argocd_app": "",
        "sonarqube_config": "",
        "trivy_config": "",
        "security_pipeline_stages": "",
    }
    result = await _graph.ainvoke(initial)
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            await client.post(f"{settings.ledger_url}/api/ledger", json={
                "project_id": req.project_id,
                "pipeline_run_id": f"devops-gen-{req.service_name}",
                "stage": "devops_generation",
                "actor": "devops-agent",
                "status": "success",
                "metadata": {"service_name": req.service_name, "service_type": req.service_type},
            })
    except Exception:
        pass
    return {
        "project_id": result["project_id"],
        "service_name": result["service_name"],
        "artifacts": {
            "gitlab_ci": result["gitlab_ci"],
            "helm_chart": result["helm_chart"],
            "kong_plugin_config": result["kong_plugin_config"],
            "argocd_app": result["argocd_app"],
            "sonarqube_config": result["sonarqube_config"],
            "trivy_config": result["trivy_config"],
        },
    }


@app.get("/health/live")
async def liveness():
    return {"status": "ok"}


@app.get("/health/ready")
async def readiness():
    return {"status": "ok"}


# ── G14: Azure DevOps Pipeline Generator ─────────────────────────────────────

import textwrap as _textwrap


class AzurePipelineRequest(BaseModel):
    project_id: str
    service_name: str
    language: str = "dotnet"   # "dotnet" | "angular" | "python"
    runs_on: str = "ubuntu-latest"


@app.post("/api/generate/azure-pipeline")
async def generate_azure_pipeline(req: AzurePipelineRequest):
    """
    Phase 15 – G14: Generates an azure-pipelines.yml for the given service.
    Stages: lint → test → security-scan → build → trivy-scan → deploy-dev → deploy-prod
    """
    if req.language == "dotnet":
        pool_image = "ubuntu-latest"
        sdk_image = "mcr.microsoft.com/dotnet/sdk:9.0"
        build_steps = _textwrap.dedent(f"""
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: 'src/{req.service_name}/**/*.csproj'
            arguments: '--configuration Release'
        """).strip()
        test_steps = _textwrap.dedent(f"""
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: 'src/{req.service_name}/**/*.Tests.csproj'
            arguments: '--configuration Release --logger trx --results-directory $(Agent.TempDirectory)/TestResults'
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            testResultsFiles: '**/*.trx'
        """).strip()
    elif req.language == "angular":
        pool_image = "ubuntu-latest"
        sdk_image = "node:22-alpine"
        build_steps = _textwrap.dedent(f"""
        - script: |
            npm ci
            npx nx build {req.service_name.lower()} --configuration production
          displayName: 'Build Angular app'
        """).strip()
        test_steps = _textwrap.dedent(f"""
        - script: npx nx test {req.service_name.lower()} --ci --reporters=default --reporters=jest-junit
          displayName: 'Run Angular tests'
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/junit.xml'
        """).strip()
    else:  # python
        pool_image = "ubuntu-latest"
        sdk_image = "python:3.12-slim"
        build_steps = _textwrap.dedent("""
        - script: pip install poetry && poetry install
          displayName: 'Install dependencies'
        """).strip()
        test_steps = _textwrap.dedent("""
        - script: poetry run pytest --junitxml=test-results/junit.xml
          displayName: 'Run Python tests'
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test-results/junit.xml'
        """).strip()

    svc_lower = req.service_name.lower()
    harbor_image = f"harbor.ai.adports.ae/orbit/{svc_lower}:$(Build.SourceVersion)"

    azure_pipeline = f"""# azure-pipelines.yml — Generated by ORBIT DevOps Agent
# Service: {req.service_name} | Language: {req.language}

trigger:
  branches:
    include: [main, "release/*"]
  paths:
    include: ["src/{req.service_name}/**"]

pool:
  vmImage: "{pool_image}"

variables:
  HARBOR_IMAGE: "{harbor_image}"
  K8S_NAMESPACE: "ai-portal"
  HELM_RELEASE: "{svc_lower}"

stages:
  - stage: Lint
    jobs:
      - job: Lint
        steps:
          - checkout: self
          - script: echo "Linting {req.service_name}..."
            displayName: 'Lint'

  - stage: Test
    dependsOn: Lint
    jobs:
      - job: UnitTest
        steps:
          - checkout: self
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'SonarQube'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: '{svc_lower}'
              cliProjectName: '{req.service_name}'
          - {build_steps}
          - {test_steps}
          - task: SonarQubeAnalyze@5
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'

  - stage: SecurityScan
    dependsOn: Test
    jobs:
      - job: SAST
        steps:
          - checkout: self
          - script: |
              echo "Checkmarx SAST scan triggered via ORBIT Checkmarx MCP"
            displayName: 'SAST Scan'

  - stage: Build
    dependsOn: SecurityScan
    jobs:
      - job: DockerBuild
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              command: 'buildAndPush'
              repository: 'orbit/{svc_lower}'
              dockerfile: 'src/{req.service_name}/Dockerfile'
              containerRegistry: 'HarborServiceConnection'
              tags: |
                $(Build.SourceVersion)
                latest

  - stage: TrivyScan
    dependsOn: Build
    jobs:
      - job: Trivy
        steps:
          - script: |
              docker run --rm aquasec/trivy:latest image \\
                --exit-code 1 --severity CRITICAL \\
                $(HARBOR_IMAGE)
            displayName: 'Trivy container scan'

  - stage: DeployDev
    dependsOn: TrivyScan
    condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))"
    jobs:
      - deployment: DeployDev
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmDeploy@0
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: 'TKG-Dev'
                    namespace: '$(K8S_NAMESPACE)-dev'
                    command: 'upgrade'
                    chartType: 'FilePath'
                    chartPath: 'charts/{svc_lower}'
                    releaseName: '$(HELM_RELEASE)'
                    arguments: '--set image.tag=$(Build.SourceVersion) --wait --timeout 3m'

  - stage: DeployProd
    dependsOn: DeployDev
    condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))"
    jobs:
      - deployment: DeployProd
        environment: 'prod'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmDeploy@0
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: 'TKG-Prod'
                    namespace: '$(K8S_NAMESPACE)'
                    command: 'upgrade'
                    chartType: 'FilePath'
                    chartPath: 'charts/{svc_lower}'
                    releaseName: '$(HELM_RELEASE)'
                    arguments: '--set image.tag=$(Build.SourceVersion) --wait --timeout 3m'
"""

    return {
        "project_id": req.project_id,
        "service_name": req.service_name,
        "language": req.language,
        "artifacts": {
            "azure_pipeline_yaml": azure_pipeline,
            "filename": "azure-pipelines.yml",
        },
    }


# ── G15: Pulumi IaC Output ────────────────────────────────────────────────────

class PulumiIacRequest(BaseModel):
    project_id: str
    service_name: str
    needs_database: bool = True
    needs_storage: bool = False
    needs_servicebus: bool = False


@app.post("/api/generate/pulumi-iac")
async def generate_pulumi_iac(req: PulumiIacRequest):
    """
    Phase 15 – G15: Generates a TypeScript Pulumi program for service-level
    Kubernetes resources (PostgreSQL via operator, MinIO bucket, RabbitMQ exchange).
    """
    svc = req.service_name
    svc_lower = svc.lower()
    svc_camel = svc.replace("-", "_").replace(" ", "_")

    resources = []

    if req.needs_database:
        resources.append(_textwrap.dedent(f"""
    // PostgreSQL database via CloudNativePG operator
    const {svc_camel}Db = new k8s.apiextensions.CustomResource("{svc_lower}-db", {{
        apiVersion: "postgresql.cnpg.io/v1",
        kind: "Cluster",
        metadata: {{
            name: "{svc_lower}-db",
            namespace: "ai-portal",
        }},
        spec: {{
            instances: 2,
            storage: {{ size: "10Gi" }},
            bootstrap: {{
                initdb: {{
                    database: "{svc_lower.replace('-', '_')}",
                    owner: "{svc_lower.replace('-', '_')}_user",
                    secret: {{ name: "{svc_lower}-db-credentials" }},
                }},
            }},
            backup: {{
                retentionPolicy: "7d",
                barmanObjectStore: {{ destinationPath: "s3://orbit-backups/{svc_lower}" }},
            }},
        }},
    }}, {{ provider: k8sProvider }});
    """).strip())

    if req.needs_storage:
        resources.append(_textwrap.dedent(f"""
    // MinIO bucket via MinIO Operator
    const {svc_camel}Bucket = new k8s.apiextensions.CustomResource("{svc_lower}-bucket", {{
        apiVersion: "minio.min.io/v2",
        kind: "Tenant",
        metadata: {{
            name: "{svc_lower}-storage",
            namespace: "ai-portal",
        }},
        spec: {{
            buckets: [{{ name: "{svc_lower}-artifacts", versioning: true }}],
            credsSecret: {{ name: "{svc_lower}-minio-credentials" }},
        }},
    }}, {{ provider: k8sProvider }});
    """).strip())

    if req.needs_servicebus:
        resources.append(_textwrap.dedent(f"""
    // RabbitMQ exchange via RabbitMQ Cluster Operator
    const {svc_camel}Exchange = new k8s.apiextensions.CustomResource("{svc_lower}-exchange", {{
        apiVersion: "rabbitmq.com/v1beta1",
        kind: "Exchange",
        metadata: {{
            name: "{svc_lower}-events",
            namespace: "ai-portal",
        }},
        spec: {{
            name: "{svc_lower}.events",
            type: "topic",
            durable: true,
            rabbitmqClusterReference: {{ name: "rabbitmq-cluster" }},
        }},
    }}, {{ provider: k8sProvider }});
    """).strip())

    pulumi_ts = _textwrap.dedent(f"""
import * as pulumi from "@pulumi/pulumi";
import * as k8s from "@pulumi/kubernetes";

// Pulumi IaC for service: {svc}
// Generated by ORBIT DevOps Agent — Phase 15 G15

const config = new pulumi.Config();
const kubeconfig = config.requireSecret("kubeconfig");

const k8sProvider = new k8s.Provider("{svc_lower}-k8s", {{
    kubeconfig: kubeconfig,
}});

{chr(10).join(resources)}

export const serviceResources = {{
    service: "{svc}",
    hasDatabase: {str(req.needs_database).lower()},
    hasStorage: {str(req.needs_storage).lower()},
    hasServiceBus: {str(req.needs_servicebus).lower()},
}};
""").strip()

    return {
        "project_id": req.project_id,
        "service_name": req.service_name,
        "artifacts": {
            "pulumi_iac_ts": pulumi_ts,
            "filename": f"src/infrastructure/k8s/services/{svc_lower}.ts",
        },
    }
